name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: poetry install
      - run: poetry run pytest --cov
      - run: poetry run flake8 .
      - run: poetry run mypy .
